// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfglYJwtDJxugQ_nVOntwk6dkQHiNRvIg',
    appId: '1:192441877347:web:eca01e81846bf378074956',
    messagingSenderId: '192441877347',
    projectId: 'rentara-d7c9c',
    authDomain: 'rentara-d7c9c.firebaseapp.com',
    storageBucket: 'rentara-d7c9c.appspot.com',
    measurementId: 'G-NVRKCSKGHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5NZDoJ0czJ1dxOjXe3fxvne5JhSW1IU',
    appId: '1:192441877347:android:20325ea54d3fc54d074956',
    messagingSenderId: '192441877347',
    projectId: 'rentara-d7c9c',
    storageBucket: 'rentara-d7c9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRHbQR70UH7Gb6oHaF5Sn2w-JS65XwU8',
    appId: '1:192441877347:ios:fc106bc4349d958b074956',
    messagingSenderId: '192441877347',
    projectId: 'rentara-d7c9c',
    storageBucket: 'rentara-d7c9c.appspot.com',
    iosBundleId: 'com.example.rentara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlRHbQR70UH7Gb6oHaF5Sn2w-JS65XwU8',
    appId: '1:192441877347:ios:d0c54f534c8d37fe074956',
    messagingSenderId: '192441877347',
    projectId: 'rentara-d7c9c',
    storageBucket: 'rentara-d7c9c.appspot.com',
    iosBundleId: 'com.example.rentara.RunnerTests',
  );
}
